### ISSUE TITLE
Nieprawidłowe odnośniki do stron prowadzących

### ISSUE THREAD

**Issue by krzyslom** [whyRconf/warsztaty#11]
Powinny być bez adresu tego repozytorium.

**Comment by MarcinKosinski** [comment]
@krzyslom nie rozumiem. Daj PR albo print screen problemu.

**Comment by krzyslom** [comment]
@MarcinKosinski w linkach do niektórych stron brakowało http:// przed adresem np. do strony Zygmunta, przez co następowało przekierowanie na https://github.com/whyRconf/warsztaty/blob/master/zstat.pl i w rezultacie 404 not found.

**Comment by MarcinKosinski** [comment]
Dziękować
